QEC._A=[];
QEC.CHARS=[
{id:"naruto",name:"Naruto Uzumaki",manga:"naruto",sexe:"H",cheveux:"blond",longueur:"court",yeux:"bleu",lunettes:false,accessoire:"bandeau",role:"heros",espece:"ninja",age:"ado",cicatrice:false,color:"#f4b942"},
{id:"sasuke",name:"Sasuke Uchiha",manga:"naruto",sexe:"H",cheveux:"noir",longueur:"court",yeux:"noir",lunettes:false,accessoire:"aucun",role:"antiheros",espece:"ninja",age:"ado",cicatrice:false,color:"#2b2f55"},
{id:"sakura",name:"Sakura Haruno",manga:"naruto",sexe:"F",cheveux:"rose",longueur:"court",yeux:"vert",lunettes:false,accessoire:"aucun",role:"heros",espece:"ninja",age:"ado",cicatrice:false,color:"#e56b9a"},
{id:"kakashi",name:"Kakashi Hatake",manga:"naruto",sexe:"H",cheveux:"blanc",longueur:"herisse",yeux:"gris",lunettes:false,accessoire:"masque",role:"soutien",espece:"ninja",age:"adulte",cicatrice:true,color:"#8a93a6"},
{id:"luffy",name:"Monkey D. Luffy",manga:"onepiece",sexe:"H",cheveux:"noir",longueur:"court",yeux:"noir",lunettes:false,accessoire:"chapeau",role:"heros",espece:"pirate",age:"ado",cicatrice:true,color:"#c0392b"},
{id:"zoro",name:"Roronoa Zoro",manga:"onepiece",sexe:"H",cheveux:"vert",longueur:"court",yeux:"noir",lunettes:false,accessoire:"aucun",role:"heros",espece:"pirate",age:"adulte",cicatrice:true,color:"#1e8449"},
{id:"nami",name:"Nami",manga:"onepiece",sexe:"F",cheveux:"orange",longueur:"long",yeux:"brun",lunettes:false,accessoire:"aucun",role:"heros",espece:"pirate",age:"adulte",cicatrice:false,color:"#e67e22"},
{id:"sanji",name:"Sanji",manga:"onepiece",sexe:"H",cheveux:"blond",longueur:"court",yeux:"bleu",lunettes:false,accessoire:"aucun",role:"heros",espece:"pirate",age:"adulte",cicatrice:false,color:"#d4ac0d"},
{id:"goku",name:"Son Goku",manga:"dbz",sexe:"H",cheveux:"noir",longueur:"herisse",yeux:"noir",lunettes:false,accessoire:"aucun",role:"heros",espece:"saiyan",age:"adulte",cicatrice:false,color:"#f39c12"},
{id:"vegeta",name:"Vegeta",manga:"dbz",sexe:"H",cheveux:"noir",longueur:"herisse",yeux:"noir",lunettes:false,accessoire:"aucun",role:"antiheros",espece:"saiyan",age:"adulte",cicatrice:false,color:"#1a237e"},
{id:"piccolo",name:"Piccolo",manga:"dbz",sexe:"H",cheveux:"chauve",longueur:"chauve",yeux:"noir",lunettes:false,accessoire:"cape",role:"heros",espece:"namek",age:"adulte",cicatrice:false,color:"#1e8449"},
{id:"tanjiro",name:"Tanjiro Kamado",manga:"demonslayer",sexe:"H",cheveux:"noir",longueur:"court",yeux:"rouge",lunettes:false,accessoire:"aucun",role:"heros",espece:"humain",age:"ado",cicatrice:true,color:"#922b21"},
{id:"nezuko",name:"Nezuko Kamado",manga:"demonslayer",sexe:"F",cheveux:"noir",longueur:"long",yeux:"rose",lunettes:false,accessoire:"bambou",role:"heros",espece:"demon",age:"ado",cicatrice:false,color:"#d98880"},
{id:"zenitsu",name:"Zenitsu Agatsuma",manga:"demonslayer",sexe:"H",cheveux:"jaune",longueur:"long",yeux:"brun",lunettes:false,accessoire:"aucun",role:"heros",espece:"humain",age:"ado",cicatrice:false,color:"#f4d03f"},
{id:"yuji",name:"Yuji Itadori",manga:"jujutsu",sexe:"H",cheveux:"rose",longueur:"court",yeux:"brun",lunettes:false,accessoire:"aucun",role:"heros",espece:"sorcier",age:"ado",cicatrice:false,color:"#e6b0aa"},
{id:"gojo",name:"Satoru Gojo",manga:"jujutsu",sexe:"H",cheveux:"blanc",longueur:"herisse",yeux:"bleu",lunettes:true,accessoire:"bandeau",role:"heros",espece:"sorcier",age:"adulte",cicatrice:false,color:"#aed6f1"},
{id:"eren",name:"Eren Jager",manga:"snk",sexe:"H",cheveux:"brun",longueur:"court",yeux:"vert",lunettes:false,accessoire:"aucun",role:"antiheros",espece:"titan",age:"ado",cicatrice:false,color:"#784212"},
{id:"mikasa",name:"Mikasa Ackerman",manga:"snk",sexe:"F",cheveux:"noir",longueur:"court",yeux:"gris",lunettes:false,accessoire:"foulard",role:"heros",espece:"humain",age:"ado",cicatrice:false,color:"#1c2833"},
{id:"levi",name:"Livai Ackerman",manga:"snk",sexe:"H",cheveux:"noir",longueur:"court",yeux:"gris",lunettes:false,accessoire:"aucun",role:"heros",espece:"humain",age:"adulte",cicatrice:false,color:"#566573"},
{id:"deku",name:"Izuku Midoriya",manga:"mha",sexe:"H",cheveux:"vert",longueur:"herisse",yeux:"vert",lunettes:false,accessoire:"aucun",role:"heros",espece:"heros",age:"ado",cicatrice:false,color:"#196f3d"},
{id:"bakugo",name:"Katsuki Bakugo",manga:"mha",sexe:"H",cheveux:"blond",longueur:"herisse",yeux:"rouge",lunettes:false,accessoire:"aucun",role:"heros",espece:"heros",age:"ado",cicatrice:false,color:"#ca6f1e"},
{id:"todoroki",name:"Shoto Todoroki",manga:"mha",sexe:"H",cheveux:"blanc",longueur:"court",yeux:"gris",lunettes:false,accessoire:"aucun",role:"heros",espece:"heros",age:"ado",cicatrice:true,color:"#e74c3c"},
{id:"light",name:"Light Yagami",manga:"deathnote",sexe:"H",cheveux:"brun",longueur:"court",yeux:"brun",lunettes:false,accessoire:"aucun",role:"vilain",espece:"humain",age:"ado",cicatrice:false,color:"#f5cba7"},
{id:"l",name:"L",manga:"deathnote",sexe:"H",cheveux:"noir",longueur:"herisse",yeux:"noir",lunettes:false,accessoire:"aucun",role:"heros",espece:"humain",age:"adulte",cicatrice:false,color:"#17202a"},
{id:"gon",name:"Gon Freecss",manga:"hxh",sexe:"H",cheveux:"noir",longueur:"herisse",yeux:"brun",lunettes:false,accessoire:"aucun",role:"heros",espece:"chasseur",age:"enfant",cicatrice:false,color:"#1e8449"},
{id:"killua",name:"Killua Zoldyck",manga:"hxh",sexe:"H",cheveux:"blanc",longueur:"herisse",yeux:"bleu",lunettes:false,accessoire:"aucun",role:"heros",espece:"chasseur",age:"enfant",cicatrice:false,color:"#d6eaf8"},
{id:"ichigo",name:"Ichigo Kurosaki",manga:"bleach",sexe:"H",cheveux:"roux",longueur:"herisse",yeux:"brun",lunettes:false,accessoire:"aucun",role:"heros",espece:"shinigami",age:"ado",cicatrice:false,color:"#e67e22"},
{id:"rukia",name:"Rukia Kuchiki",manga:"bleach",sexe:"F",cheveux:"noir",longueur:"court",yeux:"violet",lunettes:false,accessoire:"aucun",role:"heros",espece:"shinigami",age:"adulte",cicatrice:false,color:"#5b2c6f"},
{id:"edward",name:"Edward Elric",manga:"fma",sexe:"H",cheveux:"blond",longueur:"long",yeux:"jaune",lunettes:false,accessoire:"aucun",role:"heros",espece:"alchimiste",age:"ado",cicatrice:false,color:"#d4ac0d"},
{id:"saitama",name:"Saitama",manga:"opm",sexe:"H",cheveux:"chauve",longueur:"chauve",yeux:"noir",lunettes:false,accessoire:"aucun",role:"heros",espece:"heros",age:"adulte",cicatrice:false,color:"#f5b7b1"},
{id:"denji",name:"Denji",manga:"csm",sexe:"H",cheveux:"blond",longueur:"herisse",yeux:"orange",lunettes:false,accessoire:"aucun",role:"heros",espece:"devil",age:"ado",cicatrice:false,color:"#f5b041"},
{id:"power",name:"Power",manga:"csm",sexe:"F",cheveux:"blond",longueur:"long",yeux:"rouge",lunettes:false,accessoire:"cornes",role:"heros",espece:"devil",age:"ado",cicatrice:false,color:"#e74c3c"}
];
