window.QEC=window.QEC||{};
QEC.IMAGES=Object.assign(QEC.IMAGES||{},{
"ace":"https://static.wikia.nocookie.net/onepiece/images/4/4f/Portgas_D._Ace_Anime_Infobox.png/revision/latest/scale-to-width-down/239",
"aizen":"https://static.wikia.nocookie.net/bleach/images/7/7f/Aizen_Soul_Society.png",
"aki":"https://static.wikia.nocookie.net/chainsaw-man/images/c/cb/Aki_Reze_Arc_anime_design.png/revision/latest/scale-to-width-down/240",
"allmight":"https://static.wikia.nocookie.net/bokunoheroacademia/images/c/cd/Toshinori_Yagi_Golden_Age_Hero_Costume_%28Anime%29.png/revision/latest/scale-to-width-down/245",
"alphonse":"https://static.wikia.nocookie.net/fma/images/c/c3/AlManga.png/revision/latest/scale-to-width-down/348",
"annie":"https://static.wikia.nocookie.net/shingekinokyojin/images/2/2e/Annie_Leonhart_character_image.png/revision/latest/scale-to-width-down/400",
"armin":"https://static.wikia.nocookie.net/shingekinokyojin/images/2/23/Armin_Arlert_character_image.png/revision/latest/scale-to-width-down/400",
"bakugo":"https://static.wikia.nocookie.net/bokunoheroacademia/images/b/b3/Katsuki_Bakugo_Winter_Costume_2_%28Anime%29.png/revision/latest/scale-to-width-down/212",
"gaara":"https://static.wikia.nocookie.net/naruto/images/2/20/Gaara_in_Part_I.png/revision/latest/scale-to-width-down/400",
"gojo":"https://static.wikia.nocookie.net/jujutsu-kaisen/images/e/ef/Satoru_Gojo_%28Anime_2%29.png/revision/latest/scale-to-width-down/200",
"goku":"https://static.wikia.nocookie.net/dragonball/images/b/ba/Goku_anime_profile.png/revision/latest/scale-to-width-down/202",
"hinata":"https://static.wikia.nocookie.net/naruto/images/9/97/Hinata.png/revision/latest/scale-to-width-down/400",
"itachi":"https://static.wikia.nocookie.net/naruto/images/e/e9/Itachi_Child_OL.png/revision/latest/scale-to-width-down/274",
"kakashi":"https://static.wikia.nocookie.net/naruto/images/2/27/Kakashi_Hatake.png/revision/latest/scale-to-width-down/400"
});
