window.QEC=window.QEC||{};
QEC.IMAGES=Object.assign(QEC.IMAGES||{},{
"saitama":"https://static.wikia.nocookie.net/onepunchman/images/f/ff/Saitama_Manga_Profile.png/revision/latest/scale-to-width-down/340",
"genos":"https://static.wikia.nocookie.net/onepunchman/images/5/5b/Genos_Profile.png/revision/latest/scale-to-width-down/265",
"denji":"https://static.wikia.nocookie.net/chainsaw-man/images/b/b0/Denji_Reze_Arc_anime_design.png/revision/latest/scale-to-width-down/239",
"power":"https://static.wikia.nocookie.net/chainsaw-man/images/a/ac/Power_anime_design_2.png/revision/latest/scale-to-width-down/240",
"light":"https://static.wikia.nocookie.net/deathnote/images/0/05/299276.jpg/revision/latest/scale-to-width-down/170",
"l":"https://static.wikia.nocookie.net/deathnote/images/7/76/299276L.jpg/revision/latest/scale-to-width-down/181",
"gon":"https://static.wikia.nocookie.net/hunterxhunter/images/3/3e/HxH2011_EP147_Gon_Portrait.png/revision/latest/scale-to-width-down/400",
"killua":"https://static.wikia.nocookie.net/hunterxhunter/images/b/bd/HxH2011_EP147_Killua_Portrait.png/revision/latest/scale-to-width-down/400",
"ichigo":"https://static.wikia.nocookie.net/bleach/images/e/ea/Ichigo_Anime_Face.png/revision/latest/scale-to-width-down/300?cb=20221021180804",
"rukia":"https://static.wikia.nocookie.net/bleach/images/c/cf/Rukia_Anime_Face.png/revision/latest/scale-to-width-down/300?cb=20221021200812",
"todoroki":"https://static.wikia.nocookie.net/bokunoheroacademia/images/d/d8/Shoto_Todoroki_Action_5.png/revision/latest/scale-to-width-down/130",
"piccolo":"https://static.wikia.nocookie.net/dragonball/images/b/b7/Super_Hero_-_Piccolo_artwork_3.png/revision/latest/scale-to-width-down/275",
"edward":"https://static.wikia.nocookie.net/fma/images/b/b4/EdwardManga.png/revision/latest/scale-to-width-down/315",
"zenitsu":"https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/4/4f/Zenitsu_anime_right_face.png/revision/latest/scale-to-width-down/238",
"inosuke":"https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/d/d4/Inosuke_anime.png/revision/latest/scale-to-width-down/280",
"sukuna":"https://static.wikia.nocookie.net/jujutsu-kaisen/images/7/74/Sukuna_%28Volume_29%29.png/revision/latest/scale-to-width-down/261",
"chopper":"https://static.wikia.nocookie.net/onepiece/images/a/af/Tony_Tony_Chopper_Anime_Post_Timeskip_Infobox.png/revision/latest/scale-to-width-down/312",
"law":"https://static.wikia.nocookie.net/onepiece/images/4/4d/Trafalgar_D._Water_Law_Anime_Post_Timeskip_Infobox.png/revision/latest/scale-to-width-down/177"
});
